/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006971",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "secondary-container": "#3b4855",
        "error": "#ffb4ab",
        "primary-container": "#00edff",
        "inverse-on-surface": "#313030",
        "surface-container": "#201f1f",
        "on-secondary": "#25323d",
        "tertiary-fixed-dim": "#edc225",
        "on-primary-fixed-variant": "#004f55",
        "on-surface": "#e5e2e1",
        "on-tertiary": "#3c2f00",
        "on-secondary-fixed": "#101d28",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed": "#d6e4f3",
        "on-tertiary-fixed": "#231b00",
        "inverse-surface": "#e5e2e1",
        "background": "#131313",
        "secondary": "#bac8d7",
        "on-tertiary-fixed-variant": "#574500",
        "surface-container-highest": "#353534",
        "on-primary-fixed": "#001f23",
        "on-primary": "#00363b",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#b9c9cb",
        "surface-variant": "#353534",
        "on-primary-container": "#006770",
        "surface-container-high": "#2a2a2a",
        "on-error": "#690005",
        "primary-fixed-dim": "#00dbec",
        "secondary-fixed-dim": "#bac8d7",
        "tertiary-fixed": "#ffe086",
        "on-secondary-container": "#a9b7c5",
        "surface-tint": "#00dbec",
        "tertiary-container": "#ffd237",
        "on-secondary-fixed-variant": "#3b4855",
        "outline-variant": "#3b494b",
        "on-background": "#e5e2e1",
        "primary": "#d4faff",
        "outline": "#849495",
        "surface-bright": "#3a3939",
        "on-error-container": "#ffdad6",
        "surface": "#131313",
        "tertiary": "#fff2d6",
        "primary-fixed": "#88f3ff",
        "on-tertiary-container": "#715a00"
      },
      fontFamily: {
        "headline": ["Newsreader"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
